/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectominiaccess_practica;

/**
 *
 * @author emili
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
int xMouse;
int yMouse;
    public Principal() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_menu = new javax.swing.JPanel();
        p_headerCierre = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l_exit = new javax.swing.JLabel();
        l_improve = new javax.swing.JLabel();
        l_ayuda = new javax.swing.JLabel();
        l_ocultar = new javax.swing.JLabel();
        l_minimize = new javax.swing.JLabel();
        p_ladoIzq = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        js_account = new javax.swing.JSeparator();
        js_feedback = new javax.swing.JSeparator();
        js_options = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_menu.setBackground(new java.awt.Color(82, 82, 82));
        p_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_headerCierre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Microsoft_Office_Access (2).png"))); // NOI18N
        jLabel1.setText("Access");
        jLabel1.setIconTextGap(21);
        p_headerCierre.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 140, 50));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Usuario");
        p_headerCierre.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 130, 56));

        l_exit.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        l_exit.setForeground(new java.awt.Color(255, 255, 255));
        l_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_exit.setText("X");
        l_exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        p_headerCierre.add(l_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, -4, 60, 60));

        l_improve.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        l_improve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_improve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bubble speech (2).png"))); // NOI18N
        p_headerCierre.add(l_improve, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, -4, 60, 60));

        l_ayuda.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        l_ayuda.setForeground(new java.awt.Color(255, 255, 255));
        l_ayuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_ayuda.setText("?");
        l_ayuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        p_headerCierre.add(l_ayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, -4, 60, 60));

        l_ocultar.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        l_ocultar.setForeground(new java.awt.Color(255, 255, 255));
        l_ocultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_ocultar.setText("-");
        p_headerCierre.add(l_ocultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, -4, 60, 60));

        l_minimize.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        l_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimize-icon-25x25 white(3).png"))); // NOI18N
        p_headerCierre.add(l_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1159, -4, 60, 60));

        p_menu.add(p_headerCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 56));

        p_ladoIzq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/house png (2).png"))); // NOI18N
        jLabel3.setText("Home");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setInheritsPopupMenu(false);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        p_ladoIzq.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 180, 110));

        jLabel4.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new paper (2).png"))); // NOI18N
        jLabel4.setText("New");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        p_ladoIzq.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 166, 180, 110));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Open");
        p_ladoIzq.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 277, 180, 110));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        p_ladoIzq.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 513, 160, 20));

        jLabel6.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Options");
        p_ladoIzq.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 180, 40));

        jLabel7.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Account");
        p_ladoIzq.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 536, 180, 40));

        jLabel8.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Feedback");
        p_ladoIzq.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 180, 40));

        js_account.setForeground(new java.awt.Color(204, 204, 204));
        js_account.setOrientation(javax.swing.SwingConstants.VERTICAL);
        p_ladoIzq.add(js_account, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 535, 20, 40));

        js_feedback.setForeground(new java.awt.Color(204, 204, 204));
        js_feedback.setOrientation(javax.swing.SwingConstants.VERTICAL);
        p_ladoIzq.add(js_feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 577, 20, 40));

        js_options.setForeground(new java.awt.Color(204, 204, 204));
        js_options.setOrientation(javax.swing.SwingConstants.VERTICAL);
        p_ladoIzq.add(js_options, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 620, 20, 40));

        p_menu.add(p_ladoIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 720));

        getContentPane().add(p_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator js_account;
    private javax.swing.JSeparator js_feedback;
    private javax.swing.JSeparator js_options;
    private javax.swing.JLabel l_ayuda;
    private javax.swing.JLabel l_exit;
    private javax.swing.JLabel l_improve;
    private javax.swing.JLabel l_minimize;
    private javax.swing.JLabel l_ocultar;
    private javax.swing.JPanel p_headerCierre;
    private javax.swing.JPanel p_ladoIzq;
    private javax.swing.JPanel p_menu;
    // End of variables declaration//GEN-END:variables
}
